name: temp_app
description: "An App to display temperature data from a API/Websocket"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

    # State Management mit BLoC
    flutter_bloc: ^8.1.6 # BLoC
    equatable: ^2.0.5 # Vergleich von BLoC-States
    hydrated_bloc: ^9.1.5 # Persistenz von BLoC-States
    path_provider: ^2.1.5 # Speicherort für persistente Daten

    # HTTP-Client für API-Requests
    http: ^1.2.2

    # Websockets für Echtzeitkommunikation
    web_socket_client: ^0.1.5

    # JSON-Parsing und Serialisierung
    json_annotation: ^4.3.0

    # Lokale Speicherung von Daten
    shared_preferences: ^2.3.2
    sqflite: ^2.4.1

    # Diagramme
    syncfusion_flutter_gauges: ^27.1.58 
    fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
